version: '3.4'

services:
  threeplywebapi:
    image: ${DOCKER_REGISTRY-}sked
    ports:
        - "5001:80"
    
    build:
      context: .
      dockerfile: ThreeplyWebApi/Dockerfile
    depends_on: 
         - "mongo"
  mongo:
    image: "mongo"
    ports:
        - "27017:27017"